"""
Verification Agent — Telemetry Interpretation & Explanation Layer.

BOUNDARIES:
Interprets execution telemetry and compares expected vs actual behavior.
Cannot alter verification status generated by deterministic verification engine.
"""

from __future__ import annotations

from typing import Dict, Any
import structlog

from app.models.verification import VerificationResultModel
from app.config.settings import Settings

logger = structlog.get_logger(__name__)


class VerificationAgent:
    """Read-only Verification Interpretation Agent."""

    def __init__(self, settings: Settings):
        self.settings = settings

    def explain_verification(self, verification: VerificationResultModel) -> Dict[str, Any]:
        """Generate human-readable summary of telemetry verification result."""
        status = verification.status.value
        if status == "SUCCESS":
            summary = f"✅ Hardware execution verified. Actual telemetry for '{verification.device_id}' matched expected setpoint within tolerance."
        elif status == "DEVIATION":
            summary = f"⚠️ Telemetry deviation detected! Device '{verification.device_id}' error of {verification.error} kW exceeds tolerance ±{verification.tolerance} kW."
        elif status == "UNCERTAIN":
            summary = f"❓ Verification uncertain due to telemetry degradation or device communication loss."
        else:
            summary = f"❌ Verification failed for action '{verification.action_id}' on target '{verification.device_id}'."

        return {
            "verification_id": verification.verification_id,
            "status": status,
            "summary": summary,
            "confidence": verification.confidence,
            "telemetry_quality": verification.telemetry_quality,
        }
