"""
Frost OS Module 01 — Action Plan Domain Models.

Defines typed action plans, planned actions, authorizations,
audit logs, and workflow run tracking.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any

from pydantic import BaseModel, Field
from sqlalchemy import Column, DateTime, Enum, Float, ForeignKey, Index, String, Text, Boolean

from app.models.event import Base, JSON_TYPE


# ── Enumerations ──────────────────────────────────────────────────────

class PlanStatus(str, enum.Enum):
    """Action plan lifecycle status."""
    DRAFT = "DRAFT"
    AWAITING_AUTHORIZATION = "AWAITING_AUTHORIZATION"
    AUTHORIZED = "AUTHORIZED"
    REJECTED = "REJECTED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class SafetyStatus(str, enum.Enum):
    """Safety validation result."""
    PASSED = "PASSED"
    CONDITIONAL = "CONDITIONAL"
    FAILED = "FAILED"
    EMERGENCY_OVERRIDE = "EMERGENCY_OVERRIDE"


class AuthorizationDecision(str, enum.Enum):
    """Human authorization decision."""
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


# ── Planned Action ────────────────────────────────────────────────────

class PlannedAction(BaseModel):
    """
    A single structured action within an action plan.

    These are descriptive, high-level actions — NOT raw hardware commands.
    Module 08 translates approved plans into hardware commands.
    """
    action_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    action_type: str = Field(..., description="Category of action (e.g., REDUCE_LOAD, SWITCH_SOURCE)")
    target: str = Field(..., description="Target system/subsystem")
    description: str = Field(..., description="Human-readable description of what this action does")
    parameters: dict[str, Any] = Field(default_factory=dict, description="Action-specific parameters")
    priority: int = Field(default=0, description="Execution priority (lower = higher priority)")
    estimated_impact_kwh: float = Field(default=0.0, description="Estimated energy impact")
    reversible: bool = Field(default=True, description="Whether this action can be reversed")


# ── Action Plan ───────────────────────────────────────────────────────

class ActionPlan(BaseModel):
    """
    A complete action plan generated by the orchestrator.

    Contains all structured actions, safety validation results,
    and authorization requirements.
    """
    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    trigger_event_id: str = Field(..., description="Event that triggered this plan")
    decision_id: str = Field(..., description="Associated decision ID")
    station_id: str = Field(..., description="Target station")
    status: PlanStatus = PlanStatus.DRAFT
    reason: str = Field(..., description="Human-readable reason for this plan")
    actions: list[PlannedAction] = Field(default_factory=list)
    projected_reserve_kwh: float = Field(default=0.0, description="Projected reserve after plan execution")
    required_reserve_kwh: float = Field(default=0.0, description="Minimum required reserve")
    safety_status: SafetyStatus = SafetyStatus.PASSED
    requires_authorization: bool = Field(default=True, description="Whether human approval is needed")
    is_emergency: bool = Field(default=False, description="Emergency plan — may bypass authorization")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc) + timedelta(minutes=30),
    )
    metadata: dict[str, Any] = Field(default_factory=dict)


# ── Authorization ─────────────────────────────────────────────────────

class Authorization(BaseModel):
    """Record of a human authorization decision."""
    authorization_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    plan_id: str
    decision: AuthorizationDecision
    authorized_by: str = Field(..., description="Identity of the authorizer")
    reason: str = Field(default="", description="Optional reason for the decision")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ── SQLAlchemy ORM Models ─────────────────────────────────────────────

class ActionPlanRecord(Base):
    """Persistent storage for action plans."""

    __tablename__ = "action_plans"

    plan_id = Column(String(36), primary_key=True)
    trigger_event_id = Column(String(36), ForeignKey("events.event_id"), nullable=False, index=True)
    decision_id = Column(String(36), ForeignKey("decisions.decision_id"), nullable=False, index=True)
    station_id = Column(String(100), nullable=False, index=True)
    status = Column(Enum(PlanStatus, name="plan_status_enum"), nullable=False)
    reason = Column(Text, nullable=False)
    actions = Column(JSON_TYPE, nullable=False, default=[])
    projected_reserve_kwh = Column(Float, nullable=False, default=0.0)
    required_reserve_kwh = Column(Float, nullable=False, default=0.0)
    safety_status = Column(Enum(SafetyStatus, name="safety_status_enum"), nullable=False)
    requires_authorization = Column(Boolean, nullable=False, default=True)
    is_emergency = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), nullable=False, default=lambda: datetime.now(timezone.utc))
    expires_at = Column(DateTime(timezone=True), nullable=False)
    metadata_json = Column(JSON_TYPE, nullable=True)

    __table_args__ = (
        Index("ix_plans_station_status", "station_id", "status"),
    )


class AuthorizationRecord(Base):
    """Persistent storage for authorization decisions."""

    __tablename__ = "authorizations"

    authorization_id = Column(String(36), primary_key=True)
    plan_id = Column(String(36), ForeignKey("action_plans.plan_id"), nullable=False, index=True)
    decision = Column(Enum(AuthorizationDecision, name="auth_decision_enum"), nullable=False)
    authorized_by = Column(String(255), nullable=False)
    reason = Column(Text, nullable=True)
    timestamp = Column(DateTime(timezone=True), nullable=False, default=lambda: datetime.now(timezone.utc))


class AuditLogRecord(Base):
    """Append-only audit log for all orchestrator actions."""

    __tablename__ = "audit_logs"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    timestamp = Column(DateTime(timezone=True), nullable=False, default=lambda: datetime.now(timezone.utc), index=True)
    station_id = Column(String(100), nullable=False, index=True)
    correlation_id = Column(String(36), nullable=False, index=True)
    actor = Column(String(255), nullable=False)
    action = Column(String(255), nullable=False)
    resource_type = Column(String(100), nullable=False)
    resource_id = Column(String(36), nullable=True)
    details = Column(JSON_TYPE, nullable=True)
    status = Column(String(50), nullable=False, default="success")

    __table_args__ = (
        Index("ix_audit_station_ts", "station_id", "timestamp"),
    )


class WorkflowRunRecord(Base):
    """Tracks individual workflow executions."""

    __tablename__ = "workflow_runs"

    workflow_run_id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    decision_id = Column(String(36), ForeignKey("decisions.decision_id"), nullable=False, index=True)
    workflow_name = Column(String(100), nullable=False)
    station_id = Column(String(100), nullable=False)
    correlation_id = Column(String(36), nullable=False)
    status = Column(String(50), nullable=False, default="running")
    started_at = Column(DateTime(timezone=True), nullable=False, default=lambda: datetime.now(timezone.utc))
    completed_at = Column(DateTime(timezone=True), nullable=True)
    result_data = Column(JSON_TYPE, nullable=True)
    error_message = Column(Text, nullable=True)
