"""
Comprehensive Validation Result Models.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field

from app.models.safety_decision import SafetyDecisionStatus, ValidationMode, StateTransition
from app.models.reserve import ReserveCalculation
from app.models.safety_rule import ConstraintViolation
from app.models.risk import RiskAssessmentItem, RiskLevel


class ValidationResult(BaseModel):
    """Complete Output Payload generated by Module 07 Independent Plan Validator."""
    validation_id: str
    plan_id: str
    station_id: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    status: SafetyDecisionStatus
    validation_mode: ValidationMode = ValidationMode.NORMAL
    policy_version: str = "7.1.0"
    
    # Violation Details
    hard_violations: List[ConstraintViolation] = Field(default_factory=list)
    soft_violations: List[ConstraintViolation] = Field(default_factory=list)
    
    # Sub-component Status Summaries
    reserve_status: str  # "SATISFIED" or "BREACHED"
    power_status: str    # "NORMAL" or "VIOLATED"
    storage_status: str  # "HEALTHY" or "DEGRADED"
    mission_status: str  # "PROTECTED" or "COMPROMISED"
    equipment_status: str # "SAFE" or "OVERLOADED"
    data_quality_status: str # "GOOD", "DEGRADED", or "STALE"
    
    # Calculated Reserve & Risk Summaries
    reserve_calculation: ReserveCalculation
    risk_summary: List[RiskAssessmentItem] = Field(default_factory=list)
    overall_risk_level: RiskLevel = RiskLevel.LOW
    
    # Workflow Directives
    required_replan: bool = False
    is_executable: bool = False
    explanation: str
    state_transitions: List[StateTransition] = Field(default_factory=list)
    rejection_reasons: List[str] = Field(default_factory=list)
